# ==============================================================================
# Ansible Inventory - Production Environment
# ==============================================================================
# Autenticacion SSH:
#   - Con clave: docker compose run --rm ansible playbooks/site.yml --ask-pass
#   - Con SSH key: docker compose run --rm ansible playbooks/site.yml
# ==============================================================================

---
all:
  children:
    lowcode_servers:
      hosts:
        lowcode-prod:
          ansible_host: 72.62.13.157
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
